"""
Django settings for podzem_kh project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from .base import *

try:
    from .local import *
except ImportError:
    print('Не найден модуль podzem_kh.settings.local !!!  Создайте его используя local.py.skeleton')